# 基礎編テキスト（PyTorchの基礎）

## テキスト: Python基礎
1. 変数とデータ型 Pythonではデータ型を明示的に指定せずに変数を定義できます。

In [1]:
# 変数の定義
x = 10
y = 3.14
text = "Hello, PyTorch!"

print(x, y, text)  # 出力: 10 3.14 Hello, PyTorch!


10 3.14 Hello, PyTorch!


2. リストとループ リストは複数の値を保持でき、forループで処理できます。


In [2]:
# リスト
numbers = [1, 2, 3, 4, 5]

# forループ
for num in numbers:
    print(num)


1
2
3
4
5


3. 関数の定義 関数を定義して繰り返し使えるコードを作ります。

In [3]:
# 関数の例
def add(a, b):
    return a + b

result = add(5, 3)
print(result)  # 出力: 8


8


## テキスト: PyTorch基礎
1. Tensorの作成と操作 PyTorchのTensorはNumPyの配列に似ています。

In [4]:
import torch

# Tensorの作成
x = torch.tensor([1.0, 2.0, 3.0])
y = torch.tensor([4.0, 5.0, 6.0])

# 演算
z = x + y
print(z)  # 出力: tensor([5., 7., 9.])


tensor([5., 7., 9.])


2. 自動微分（autograd）の基本 PyTorchでは自動微分機能を使って勾配を計算できます。

In [5]:
# Tensorの定義（勾配を計算するために requires_grad=True）
x = torch.tensor(2.0, requires_grad=True)

# 計算
y = x**2 + 3*x + 1

# 勾配の計算
y.backward()

# xに対する微分値を表示
print(x.grad)  # 出力: tensor(7.)


tensor(7.)


# 基礎編例題
### 例題1: Tensorの基本操作
以下のコードを完成させてください：

- Tensor a と b を作成します（値は [1, 2, 3] と [4, 5, 6]）。

- それらの和と積を計算し、結果を表示してください。

In [6]:
import torch

# ここに Tensor を定義してください

# 和の計算


# 積の計算


# 結果の表示


期待される出力:

tensor([5, 7, 9])

tensor([4, 10, 18])

### 例題2: 勾配計算
以下の手順でコードを完成させてください：

- Tensor x を作成（値は 3.0、requires_grad=True を設定）。

- 関数 y = x**3 - 2*x を計算。

- y の勾配を計算して表示。

In [7]:
import torch

# ここに Tensor を定義してください

# 関数の計算


# 勾配の計算


# 勾配の出力


期待される出力:

tensor(25.)